services:
  tg-bot:
    build: .
    container_name: kachbot
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./users.db:/app/users.db
    ports:
      - "3000:3000"