services:
  tg-bot:
    build: .
    container_name: kachbot
    restart: always
    network_mode: "host"
    env_file:
      - /root/Training-tg-bot/.env
    volumes:
      - /root/Training-tg-bot/users.db:/app/data/users.db